name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Default metrics
          uses: lowlighter/metrics@master
          with:
            filename: metrics.base.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: header, activity, community, repositories


        - name: Indepth analysis
          uses: lowlighter/metrics@master
          with:
            filename: metrics.plugin.languages.indepth.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_languages: yes
            plugin_languages_ignored: >-
              html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
              gnuplot
            plugin_languages_indepth: yes
            plugin_languages_details: lines, bytes-size
            plugin_languages_limit: 10
            plugin_languages_analysis_timeout: 50


        - name: Display
          uses: lowlighter/metrics@master
          with:
            filename: metrics.plugin.achievements.compact.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_achievements: yes
            plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
              scripter, packager, explorer, infographile, manager
            plugin_achievements_display: detailed
            plugin_achievements_threshold: X


        # - name: WakaTime
        #   uses: lowlighter/metrics@latest
        #   with:
        #     filename: metrics.plugin.wakatime.svg
        #     token: NOT_NEEDED
        #     base: ""
        #     plugin_wakatime: yes
        #     plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}      # Required
        #     plugin_wakatime_days: 7                                   # Display last week stats
        #     plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
        #     plugin_wakatime_limit: 4                                  # Show 4 entries per graph
        #     plugin_wakatime_url: http://wakapi.dev                    # Wakatime url endpoint
        #     plugin_wakatime_user: .user.login












